version: '3.8'
services:

  mariadb:
    image: mariadb:iniesta
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:iniesta
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  nginx:
    image: nginx:iniesta
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: '/home/azgaoua/data/mariadb'
      o: 'bind'
      type: 'none'

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: '/home/azgaoua/data/wordpress'
      o: 'bind'
      type: 'none'

networks:
  inception:
    name: inception
    driver: bridge
