version: '3.8'
services:
  mariadb:
    image: mariadb:iniesta
    build : ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  nginx:
    image: nginx:iniesta
    build : ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    image: wordpress:iniesta
    build : ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb 
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: '/home/data/mariadb'
      o : 'bind'
      type : 'none'

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: '/home/data/wordpress'
      o : 'bind'
      type : 'none'

# networks:
networks:
  inception:
    driver: bridge


# services:
#   nginx:
#     image: nginx:azgaoua
#     container_name: nginx
#     networks:
#       - inception
#     depends_on:
#       - wordpress
#     build: ./requirements/nginx
#     env_file: .env
#     volumes:
#       - wordpress:/var/www/html
#     restart: always
#     ports:
#       - "443:443"

#   mariadb:
#     image: mariadb:azgaoua
#     container_name: mariadb
#     networks:
#       - inception
#     build: ./requirements/mariadb
#     env_file: .env
#     volumes:
#       - mariadb:/var/lib/mysql
#     restart: always

#   wordpress:
#     depends_on:
#       - mariadb
#     image: wordpress:azgaoua
#     container_name: wordpress
#     networks:
#       - inception
#     build: ./requirements/wordpress
#     env_file: .env
#     volumes:
#       - wordpress:/var/www/html
#     restart: always

# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/azgaoua/data/wordpress'
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/azgaoua/data/mariadb'

# networks:
#   inception:
#     driver: bridge