version: '3.8'

services:

  mariadb:
    image: mariadb:azgaoua
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:azgaoua
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    secrets:
      - MYSQL_PASSWORD
      - WP_ADMIN_P
      - WP_U_PASS
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx:azgaoua
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/azgaoua/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/azgaoua/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  MYSQL_PASSWORD:
    file: ./../secrets/MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./../secrets/MYSQL_ROOT_PASSWORD
  WP_ADMIN_P:
    file: ./../secrets/WP_ADMIN_P
  WP_U_PASS:
    file: ./../secrets/WP_U_PASS

